# Generated by Django 2.2 on 2020-01-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studies', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('corr_file', models.FileField(upload_to='')),
                ('knowledge_capture_sample_file', models.FileField(upload_to='')),
                ('knowledge_capture_gene_file', models.FileField(upload_to='')),
                ('additional_filter_file', models.FileField(upload_to='')),
                ('tag', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
