# Generated by Django 2.2 on 2020-01-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studies', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
            ],
        ),
    ]
